### ISSUE TITLE
java.lang.RuntimeException: 

### ISSUE THREAD

**Issue by zhangzzqq** [jeasonlzy/ImagePicker#1]
把你的代码（压缩文件）下载下来，报错 RuntimeException: java.lang.RuntimeException: java.io.UTFDataFormatException: malformed input around byte 1，请问这样怎样解决？

**Comment by zhangzzqq** [comment]
错误记录  ：18:09:53 RuntimeException: java.lang.RuntimeException: java.io.UTFDataFormatException: malformed input around byte 1
18:09:53 Gradle sync started
18:09:56 RuntimeException: java.lang.RuntimeException: java.io.UTFDataFormatException: malformed input around byte 3

**Comment by zhangzzqq** [comment]
按照你下面的步骤集成又报错 Android gradle build Error:(9, 0) Gradle DSL method not found: 'compile()'.

**Comment by jeasonlzy0216** [comment]
首先正常是可以直接导入的。我自己下载导入了一遍是没有任何问题的，不用修改可以直接运行，Gradle DSL method not found: 'compile()'. 这个问题应该是你集成的时候出了点问题，你可以把zip包解压后不用运行，在studio选择 File -> new -> Import Module -> 选择刚刚解压路径中的 library_ImagePicker 文件夹，然后等待导入完成。这样就可以了，至于下载的demo不能运行，可能你是studio 环境的问题，在我studio根节点中的build.gradle中是这样的 classpath 'com.android.tools.build:gradle:1.5.0'，使用的1.5.0，你的studio中应该用1.2.0以上的版本才可以。

**Comment by jeasonlzy0216** [comment]
刚更新了下，把项目传到了jCenter上，使用的话直接 
compile 'com.lzy.widget:imagepicker:0.1.0'
这样就可以用了。不用导包了。
