### ISSUE TITLE
打开相册，报出异常

### ISSUE THREAD

**Issue by sxhjlzl** [jeasonlzy/ImagePicker#100]
Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.

**Comment by nanchen2251** [comment]
额，这个是ImageLoader那，我主要还没更新框架的代码上去，你暂时把ImageLoader的初始化改为以前那样，比如：
Glide.with(activity)                             //配置上下文
                .load(Uri.fromFile(new File(path)))      //设置图片路径(fix #8,文件名包含%符号 无法识别和显示)
                .error(R.mipmap.default_image)           //设置错误图片
                .placeholder(R.mipmap.default_image)     //设置占位图片
                .diskCacheStrategy(DiskCacheStrategy.ALL)//缓存全尺寸
                .into(imageView);

把load的参数换回原来的，就不会出现问题了。
