### ISSUE TITLE
provider冲突，0.4.6还是存在

### ISSUE THREAD

**Issue by ench0218** [jeasonlzy/ImagePicker#104]
provider冲突，0.4.6还是存在

**Comment by nanchen2251** [comment]
具体冲突日志？

**Comment by ench0218** [comment]
![image](https://cloud.githubusercontent.com/assets/13462269/24337674/0e0f7b08-12d2-11e7-9861-f061fbb03c07.png)

**Comment by ench0218** [comment]
两个app都用ImagePicker就会报这个错
