### ISSUE TITLE
一个放大图片的闪退

### ISSUE THREAD

**Issue by supercwn** [jeasonlzy/ImagePicker#106]
步骤：选择一张图片——预览（进去图片放大）——取消选择——点击图片，就闪退了。
日记如下：The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 0 Pager id: com.lzy.imagepickerdemo:id/viewpager Pager class: class com.lzy.imagepicker.view.ViewPagerFixed Problematic adapter: class com.lzy.imagepicker.adapter.ImagePageAdapter

**Comment by nanchen2251** [comment]
你好，不太明白你的步骤。请添加QQ群118116509，并把步骤录制成视频发给我
