### ISSUE TITLE
FileProvider存在问题，相同的authorities

### ISSUE THREAD

**Issue by shejishi** [jeasonlzy/ImagePicker#107]
`<provider android:name="android.support.v4.content.FileProvider"
android:authorities="com.lzy.imagepicker.provider"
android:exported="false"
android:grantUriPermissions="true" >
` 
多个应用存在相同的authorities之后，我的魅族手机就安装不了，能不能将authorities设置为软编码的形式动态获取值？

**Comment by nanchen2251** [comment]
解决了。在测试一下
