### ISSUE TITLE
使用时，选择图片，点击预览，出现崩溃情况

### ISSUE THREAD

**Issue by zhaoshunchen** [jeasonlzy/ImagePicker#110]
提示 相册数据弱引用为空！请检查！ (ImagePreviewBaseActivity.java:54)

**Comment by nanchen2251** [comment]
你一定是引用错版本了。现在应该更改了，应该不会提示这个了。这个是我之前测试的一个自定义异常。现在都删除了的。

**Comment by zhaoshunchen** [comment]
不好意思，才看见最新版的

**Comment by nanchen2251** [comment]
好的。

**Comment by zhaoshunchen** [comment]
但是在新版本中发现了一个新的问题，在bitmapUtil类当中rotateBitmapByDegree该方法中BitmapFactory.decodeFile 直接通过该方法获取图片会出现OOM。建议把图片压缩以后再加载到bitmap当中

**Comment by nanchen2251** [comment]
谢谢指出，会做修复。
