### ISSUE TITLE
有些图片不存在了，但是相册里有缓存

### ISSUE THREAD

**Issue by pardonhan** [jeasonlzy/ImagePicker#118]
有些图片不存在了，但是还是会显示出来，进行网络上传时会失败，单张选择时可以进行裁剪另存，但多张时怎么进行处理？

**Comment by nanchen2251** [comment]
这个问题，暂时没有找到原因，建议你在上传的时候做一下筛选处理，后面我会在框架中直接筛选。需要等候一定的时间。另外，对于裁剪，暂时是不支持多张的

**Comment by pardonhan** [comment]
嗯，好的，谢谢
