### ISSUE TITLE
完全仿微信页,图片删除时,吧图片放大滑动报错

### ISSUE THREAD

**Issue by yangyu92** [jeasonlzy/ImagePicker#12]
完全仿微信页,图片删除时,吧图片放大滑动报错
com.lzy.imagepicker.view.ViewPagerFixed.onInterceptTouchEvent(ViewPagerFixed.java:32)

**Comment by jeasonlzy0216** [comment]
0.2.4 修复。。

**Comment by yangyu92** [comment]
厉害!赞一个
