### ISSUE TITLE
请教！！要用此框架设置一张头像该怎么调用？？

### ISSUE THREAD

**Issue by hymbo** [jeasonlzy/ImagePicker#120]
点击头像图片占位图后把选中的照片回填到占位图该怎么调用，我看了demo只是有关列表中的调用

**Comment by nanchen2251** [comment]
你好，不太明白你的意思。

**Comment by hymbo** [comment]
你好，感谢抽空来解答！我的意思是，如果我的页面上只有一个Imageview控件（或者自定义的圆形Imageview控件），我点击了这个控件之后，用ImagePicker库打开相机拍照或者从相册选择相片并却确定后要直接填充到该Imageview控件上，应该怎么调用什么相关方法？是否一定要通过一个apapter+listview或apapter+recyclerview进行设置呢？

**Comment by nanchen2251** [comment]
详细请查看demo，demo中那个加号的图片和你所说的是一个意思。

**Comment by hymbo** [comment]
可能你对我说的问题理解上有一定的偏差了，前面也说了是一个类似实现头像这样的需求，仅且只有一张图片，如果按照demo中的参考，那么是为了实现填充一个头像的Imageview控件也得实现一个apapter加一个RecyclerView/ListVIew了，这用起来不是反而复杂？

**Comment by nanchen2251** [comment]
那你这个问题我感觉不用本框架会更加好解决。毕竟你拍照只需要很少的代码，调用系统相册就更加简单了。就算你用本框架，本框架已经把图片的路径返还给你了。那你通过路径肯定是可以转换出一个Bitmap的，你转换为bitmap设置进去就好了吧。

**Comment by hymbo** [comment]
感谢耐心指导了！
