### ISSUE TITLE
ImagePicker设置问题

### ISSUE THREAD

**Issue by GuoZhaoHui628** [jeasonlzy/ImagePicker#135]
我现在是这样一种情况，一个activity中有需要添加一张图片，又需要多选添加多张图片，但是这个ImagePicker怎样设置呢。我是这样设置的，首先将 
ImagePicker imagePicker = ImagePicker.getInstance();写在属性上，然后将他们公共的设置抽出来设置好，比如
        imagePicker.setImageLoader(new GlideImageLoader());   //设置图片加载器
        imagePicker.setShowCamera(true);                      //显示拍照按钮
        imagePicker.setCrop(false);                           //允许裁剪（单选才有效）
然后在添加多张图片的事件地方设置 imagePicker.setSelectLimit(4);              //选中数量限制 和  imagePicker.setMultiMode(true);
添加一张图片设置 imagePicker.setMultiMode(false);
但是这样写好后，总是前面的会给后面的设置覆盖，比如如果我先点击单选的，没问题，但是点击多选结果显示还是单选的相册。这是怎样设置的，看到麻烦解答下，谢谢

**Comment by nanchen2251** [comment]
因为是单例的，所以肯定会覆盖的，建议可以尝试每次单选或者多选的时候再设置一下imagePicker的属性。

**Comment by GuoZhaoHui628** [comment]
嗯 ok了，谢谢了
