### ISSUE TITLE
ImageCropActivity里的CropImageView.setOnBitmapSaveCompleteListener(this)导致的内存泄漏。

### ISSUE THREAD

**Issue by z332406259** [jeasonlzy/ImagePicker#142]
由于CropImageView这个类里面的OnBitmapSaveCompleteListener是静态的，会持有activity的引用。处理办法。要么不要让ImageCropActivity实现接口，用匿名类的方式设置监听。或者在ImageCropActivity销毁之前把监听设置为空。

**Comment by nanchen2251** [comment]
有问题。欢迎贡献源码呀，sorry，最近暂时抽不出空做维护处理。你们都可以帮着维护的。
