### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by realIdiot** [jeasonlzy/ImagePicker#161]
demo也是很多图片显示不出来，我的app也是很多图片显示不出来，都是黑的。有遇到这样的问题吗

**Comment by realIdiot** [comment]
GlideImageLoader  图片太大好像显示不了 diskCacheStrategy(DiskCacheStrategy.NONE) 改成这样好像可以了

**Comment by nanchen2251** [comment]
可以就好呀。
