### ISSUE TITLE
选好照片点击完成后如何相册清除选中状态呢

### ISSUE THREAD

**Issue by giantss** [jeasonlzy/ImagePicker#171]
插件选好照片后点击完成，如何清空相册的选中状态呢（回到相册初始化的界面）

**Comment by nanchen2251** [comment]
不是在群里回你了吗？直接查看Demo示例中的WxDemoActivity文件。

**Comment by giantss** [comment]
没收到你的群回复啊  谢谢   我怎么没有在WxDemoActivity文件中看到问题的代码

**Comment by nanchen2251** [comment]
我的意思是你通过下载框架的demo，运行仿微信页面，应该是该Activity和你所提的功能需求一致，所以诚恳地希望你先查看后再对比你哪里有所不同。

**Comment by giantss** [comment]
好的  谢谢你  已经解决了

**Comment by nanchen2251** [comment]
不谢，应该的。以后用框架，自己发现了问题，建议先看下官方Demo是否存在这样的问题。

**Comment by giantss** [comment]
貌似相机拍照键有一些兼容性问题，其他机型我没怎么测试 我用的是Genymotion模拟器 Nexus5 5.0.0上相机打不开

**Comment by nanchen2251** [comment]
建议不要使用模拟器，模拟器在一定意义上有些东西是无法比拟真机的，你可以使用腾讯云真机进行测试查看。

**Comment by giantss** [comment]
好的。我是四川南充的 现在在杭州  很高兴认识你。/握手

**Comment by nanchen2251** [comment]
四川成都。很高兴认识你。快干活去吧，我这会儿活堆得山一样高。

**Comment by giantss** [comment]
南城你好  后面这个插件打算把图片压缩加进去吗

**Comment by nanchen2251** [comment]
图片压缩并不是所有人的需求，因为如果你不上传，是不必要压缩的，所以要使用压缩请使用另外一个库CompressHelper
