### ISSUE TITLE
让拍照得到的照片，在ImagePicker里成为选中状态

### ISSUE THREAD

**Issue by njleonzhang** [jeasonlzy/ImagePicker#178]
我拍了一张照片得到一个ImageItem，然后我通过`EXTRAS_IMAGES`参数吧这个值传给了ImageGridActivity并打开。ImageGridActivity里能看到我拍的照片，但是并没有处于选中状态，但是右上角的选中图片个数里缺显示1, 请问我要怎么处理拍照得到的ImageItem，才能让ImageGridActivity里我的这个照片处于选中状态呢？

**Comment by nanchen2251** [comment]
这些小需求请自己实现。开源项目不能满足所有人的各种需求呀。

**Comment by njleonzhang** [comment]
看到了。。。。你是通过contain来判断的，我自己实现吧。。
```
                boolean checked = mSelectedImages.contains(imageItem);
```

**Comment by njleonzhang** [comment]
我给你提PR你要么？

**Comment by nanchen2251** [comment]
你应该先PR，让别人看效果。

**Comment by njleonzhang** [comment]
好的，有空提一个

**Comment by shitou9999** [comment]
你确定你前几天提的解决了问题？我试着不可以呢

**Comment by njleonzhang** [comment]
@shitou9999 我提了PR https://github.com/jeasonlzy/ImagePicker/pull/182。

**Comment by nanchen2251** [comment]
现在我被撤职了，没法给你merge了，你联系廖子尧吧。 @njleonzhang

**Comment by njleonzhang** [comment]
@nanchen2251 维护个git还能被撤职的咯。。。

**Comment by nanchen2251** [comment]
@njleonzhang 也是因为我没啥时间，也可能是我做的不好，哈哈。其实我也不知道为什么。就突然发现没有写入权限了。

**Comment by njleonzhang** [comment]
@nanchen2251 Thanks anyway, 大家都很忙，能做开源还是不容易的，感谢

**Comment by nanchen2251** [comment]
@njleonzhang 向廖总和严总等开源人士学习，一起开源，我近期工作缓下来了，又开始开源了。

**Comment by njleonzhang** [comment]
@nanchen2251 我也有一些，就是star不多
