### ISSUE TITLE
ImageFolderAdapter 中 getItemViewHeight这种方式 低端机会获取不到高度会闪退

### ISSUE THREAD

**Issue by z8806c** [jeasonlzy/ImagePicker#19]
public int getItemViewHeight() {
        View itemView = mInflater.inflate(R.layout.adapter_folder_list_item, null);
        itemView.measure(0, 0);
        return itemView.getMeasuredHeight();
    }

直接写死item高

**Comment by jeasonlzy0216** [comment]
这里主要是优化相册列表比较少的情况。。

**Comment by z8806c** [comment]
嗯嗯 只是提醒下 我这边用户在使用时 出现闪退  追踪到这里    我已经写死了item的高度

**Comment by jeasonlzy0216** [comment]
感谢。。如果有问题，欢迎继续反馈。。
