### ISSUE TITLE
6.0 的系统中有些会出现下面的异常然后就崩了.有些6.0就不出现..奇怪

### ISSUE THREAD

**Issue by huangyuan1113** [jeasonlzy/ImagePicker#21]
Permission Denial: reading com.android.providers.media.MediaProvider

华为的6.0会出现

**Comment by jeasonlzy0216** [comment]
权限问题。你加上6.0 的动态权限就好了。。

**Comment by zhanghehe** [comment]
6.0 拍照也会有问题

**Comment by huangyuan1113** [comment]
我知道是6.0的动态权限的问题, 不过我是想要是把这个做到这库里不是更省事些吗 ^_^
