### ISSUE TITLE
预览黑屏

### ISSUE THREAD

**Issue by realchen** [jeasonlzy/ImagePicker#215]
方式1
Intent intent = new Intent(this, ImagePreviewActivity.class);

        intent.putExtra(ImagePicker.EXTRA_SELECTED_IMAGE_POSITION, position);
        intent.putExtra(ImagePicker.EXTRA_IMAGE_ITEMS, imgs);
        intent.putExtra(ImagePreviewActivity.ISORIGIN, false);
        intent.putExtra(ImagePicker.EXTRA_FROM_ITEMS, true);
        startActivityForResult(intent, ImagePicker.REQUEST_CODE_PREVIEW);
方式2
 Intent intentPreview = new Intent(this, ImagePreviewDelActivity.class);
        intentPreview.putExtra(ImagePicker.EXTRA_IMAGE_ITEMS, imgs);
        intentPreview.putExtra(ImagePicker.EXTRA_SELECTED_IMAGE_POSITION, position);
        intentPreview.putExtra(ImagePicker.EXTRA_FROM_ITEMS, true);
        startActivityForResult(intentPreview, ImagePicker.REQUEST_CODE_PREVIEW);
使用这2种方式进行预览都是黑屏，直接在选择图片界面打开具体图片也是黑屏，这是什么原因

**Comment by JadynChan** [comment]
PhotoView photoView = new PhotoView(mActivity);
        ImageItem imageItem = images.get(position);
        imagePicker.getImageLoader().displayImagePreview(mActivity, imageItem.path, photoView, screenWidth, screenHeight);
        photoView.setOnPhotoTapListener(new PhotoViewAttacher.OnPhotoTapListener() {
            @Override
            public void onPhotoTap(View view, float x, float y) {
                if (listener != null) listener.OnPhotoTapListener(view, x, y);
            }
        });
        container.addView(photoView);


预览的回调是displayImagePreview，你估计没写
