### ISSUE TITLE
裁剪图片界面裁剪部分没有高亮显示

### ISSUE THREAD

**Issue by bypain** [jeasonlzy/ImagePicker#24]
裁剪部分没有高亮显示，整个都是暗的，体验不大好哦

**Comment by bypain** [comment]
应该是系统问题，有的手机会，有的不会

**Comment by jeasonlzy0216** [comment]
这个和机型有关系，裁剪的控件使用了  canves.clipPath() 这个方法，它只允许关闭硬件加速才能使用，目前手机基本都是关闭了硬件加速的，只有极少部分手机默认开启的，你可以使用最新的 0.3.0 版本，对这个问题做了修复。。
