### ISSUE TITLE
完全仿微信demo中使用UILImageLoader,返回的缩略图是一张模糊的图片用GlideImageLoader不会，不知是什么原因？

### ISSUE THREAD

**Issue by mzx123** [jeasonlzy/ImagePicker#25]

**Comment by jeasonlzy0216** [comment]
demo是正常的。。不会返回缩略图的。。你看看你可能修改了一些位置。。

**Comment by mzx123** [comment]
我直接在adapter 里用UIL显示返回的路径图片了。谢谢大神指点

**Comment by hejun311** [comment]
你在void displayImage这个方法中手动设置图片一个宽高就可以了  例如width 720 height 1280  应该就可以了  可以去试下
