### ISSUE TITLE
多选时，使用PicassoImageLoader会出现图片重新加载的现象，使用GlideImageLoader则不会

### ISSUE THREAD

**Issue by hust201010701** [jeasonlzy/ImagePicker#29]
**jeasonlzy0216：**

你好，首先感谢你写了一个非常好用的图片选择库。
但是我在使用的过程中，发现一个问题：

> 多选时，使用PicassoImageLoader会出现图片重新加载的现象，使用GlideImageLoader则不会。

后来发现是这句代码的问题：

```
.memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_CACHE)
```

删除掉之后，即可正常选取，而且从AndroidStudio中看到，耗用内存更少了。

望知悉。

**Comment by jeasonlzy0216** [comment]
好的。谢谢。。picasso 我用的不多。demo只是为了演示可以使用picasso加载，所以细节可能没注意。。

**Comment by yangzixiao** [comment]
我也遇到了这样的问题，想问作者呢，没想到有前辈探路了，测试下试试

**Comment by nanchen2251** [comment]
已经解决。
