### ISSUE TITLE
PicassoImageLoader android 6.0 闪退出现白色界面返回主界面

### ISSUE THREAD

**Issue by xiaokus** [jeasonlzy/ImagePicker#32]

**Comment by jeasonlzy0216** [comment]
异常信息贴一下吧。。。

**Comment by xiaokus** [comment]
就PicassoImageLoader  时出现这种异常其他 imageloader 正常
 java.lang.IllegalArgumentException
At least one dimension has to be positive number.
com.squareup.picasso.Request$Builder.resize(Request.java:305)
 com.squareup.picasso.Request$Builder.resize(Request.java:305)
 com.squareup.picasso.RequestCreator.resize(RequestCreator.java:219)
com.haowuye.haowuyecom.utils.imageloader.PicassoImageLoader.displayImage(PicassoImageLoader.java:26)
com.haowuye.haowuyecom.adapter.ImagePickerAdapter$SelectedPicViewHolder.bind(ImagePickerAdapter.java:101)
com.haowuye.haowuyecom.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:74)
com.haowuye.haowuyecom.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:27)
android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
9 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
10 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)

**Comment by CtThunder** [comment]
PicassoImageLoader  
.load(Uri.fromFile(new File(path)))//注意uri 否则报错闪屏

**Comment by nanchen2251** [comment]
已经解决。
