### ISSUE TITLE
安裝到系統 4.1.2 的機器時，無法顯示圖片

### ISSUE THREAD

**Issue by eimori** [jeasonlzy/ImagePicker#37]
如題。

將Demo apk 安裝至 android 4.1.2 時，皆無法顯示內存圖片
開啟拍照功能拍攝之後，照片也無回存，使用檔案瀏覽器也找不到圖片

請問有什麼辦法可以讓 android 4.1.2 也能使用嗎？

**Comment by jeasonlzy** [comment]
这个和系统版本没有关系。可能和rom有关系。。具体机型哪款。

**Comment by eimori** [comment]
目前有兩支機型發生這樣的狀況
附上型號與系統截圖
1.Sony Xperia S 
[http://imgur.com/a/iMzGb](url)

2.SHARP SH631W
[http://imgur.com/a/uOQGe](url)

這樣資訊是否足夠？

因為無法順利抓到圖片，所以我也嘗試安裝GalleryFinal做測試
測試結果則是成功抓到內部圖片

**Comment by jeasonlzy** [comment]
ok。谢谢。。后续我会测试。。

**Comment by eimori** [comment]
再麻煩您測試了，謝謝

**Comment by TracesDream** [comment]
@eimori @jeasonlzy   问题是出在版本判断上



if (Build.VERSION.SDK_INT > Build.VERSION_CODES.JELLY_BEAN) {
			if (checkPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
				new ImageDataSource(this, null, this);
			} else {
				ActivityCompat.requestPermissions(this, new String[] { Manifest.permission.WRITE_EXTERNAL_STORAGE }, REQUEST_PERMISSION_STORAGE);
			}
		}


把>改成>=

**Comment by DizzyYang** [comment]
@eimori @jeasonlzy 

这是问题所在。

if (Build.VERSION.SDK_INT > Build.VERSION_CODES.JELLY_BEAN) {
            if (checkPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
                new ImageDataSource(this, null, this);
            } else {
                ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_PERMISSION_STORAGE);
            }
        }else{
            new ImageDataSource(this, null, this);
        }
