### ISSUE TITLE
删除项操作

### ISSUE THREAD

**Issue by slimvan** [jeasonlzy/ImagePicker#39]
多选图片后，图片显示在RecyclerView上。我在item布局中放了一个删除按钮，在adapter中做了监听，当点击时selImages.remove(position) 然后刷新adapter  但是这样子删掉图片后，在列表显示仍会留有一个待添加的图片。。 类似于：我添加8个图片后，再一一删除，列表会留有8个待添加的图片。。希望能指点一下。谢谢

**Comment by devilyaos** [comment]
你应该自己隐藏删掉的控件吧
