### ISSUE TITLE
fresco

### ISSUE THREAD

**Issue by RuijiePan** [jeasonlzy/ImagePicker#4]
不兼容fresco吗？
还有就是在相册选择图片的时候，如果没点到勾，进行很容易点到预览。从那里进入预览就白屏，然后跳回主界面。

**Comment by jeasonlzy0216** [comment]
兼容。需要自己写 ImageLoader 的实现。在代码中设置为你的实现就可以了。。白屏那个没遇到过，如果是异常的话，有没有 异常log。

**Comment by RuijiePan** [comment]
白屏那个倒是没有报错。直接跳回主界面。图片选择的选区太小，很容易就点成预览。点击预览进不去，我自己把点击图片预览的整合范围设置成选择图片。                           选择图片之后，如何设置图片自动压缩，选不选择原图都没看到区别。默认配置的好像是裁剪之后才有压缩。               我之前用的是galleryfinal，里面对兼容fresco有特殊处理。你在demo里面可以把fresco的imageloader也加上去。

**Comment by jeasonlzy0216** [comment]
那个原图按钮只是个ui，没有做功能。后期升级再增加。你说的其他问题，在升级的时候，一并解决。
