### ISSUE TITLE
ImageGridActivity单击图片跳转ImagePreviewActivity如果相册图片过多闪退的问题

### ISSUE THREAD

**Issue by tonvchong** [jeasonlzy/ImagePicker#6]
ImageGridActivity单击图片跳转ImagePreviewActivity如果相册图片过多闪退的问题。

intent.putExtra(ImagePicker.EXTRA_IMAGE_ITEMS, imagePicker.getCurrentImageFolderItems());
使用intent传递数据存在大小限制，而当前相册可能很大所以会导致当前页面的闪退。

我的解决办法：使用单例传递数据
DataHolder.getInstance().setData(imagePicker.getCurrentImageFolderItems());

**Comment by jeasonlzy0216** [comment]
确实存在。。下次更新优化。。感谢提出。。

**Comment by huangzhongping** [comment]
这个问题解决了吗，可以使用单例传值吗

**Comment by huangzhongping** [comment]
DataHolder这个类是什么

**Comment by 17773737673** [comment]
http://stackoverflow.com/questions/12819617/issue-passing-large-data-to-second-activity
