### ISSUE TITLE
demo 是会闪退的，如果选择的是PicassoImageLoader

### ISSUE THREAD

**Issue by cyqluowang** [jeasonlzy/ImagePicker#65]
并且图片选择会抖动

**Comment by Pgrammerybj** [comment]
如果你使用PicassoImageLoader来加载图片的话，出现闪烁的原因在于缓存的问题。你只需要将PicassoImageLoader中 .memoryPolicy(MemoryPolicy.NO_CACHE, MemoryPolicy.NO_STORE)这一个配置注释掉，或者替换为GlideImageLoader即可。希望能帮到你

**Comment by nanchen2251** [comment]
已解决。
