### ISSUE TITLE
Android N 上 报错：android.os.FileUriExposedException

### ISSUE THREAD

**Issue by Alfred-Sky** [jeasonlzy/ImagePicker#69]
小米5开发板，android 7.0，打开摄像头页面闪退

**Comment by Alfred-Sky** [comment]
解决啦！
1：
在清单文件里添加
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="包名.fileProvider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
2.在res目录下新建一个xml文件夹，并且新建一个file_paths的xml文件
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path path="Android/data/com.lzy.imagepickerdemo/" name="files_root" />
    <external-path path="." name="external_storage_root" />
</paths>
3,if (Build.VERSION.SDK_INT>=Build.VERSION_CODES.N){
                    Uri photoURI = FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".provider", createImageFile());
                }else {
                    Uri photoURI = Uri.fromFile(createImageFile());
                }

**Comment by CNCFOX** [comment]
解决代码已经提交给，等待合并，如果急需请到Pull Request 中查找
