### ISSUE TITLE
图片预览的时候，当一个文件夹下图片太多，直接传递图片集合会报异常

### ISSUE THREAD

**Issue by hym2111** [jeasonlzy/ImagePicker#70]
Intent intent = new Intent(ImageGridActivity.this, ImagePreviewActivity.class);
            intent.putExtra(ImagePicker.EXTRA_SELECTED_IMAGE_POSITION, position);
            intent.putExtra(ImagePicker.EXTRA_IMAGE_ITEMS, imagePicker.getCurrentImageFolderItems());
            intent.putExtra(ImagePreviewActivity.ISORIGIN, isOrigin);
            startActivityForResult(intent, ImagePicker.REQUEST_CODE_PREVIEW);

**Comment by CNCFOX** [comment]
解决代码已经提交给，等待合并，如果急需请到Pull Request 中查找

**Comment by nanchen2251** [comment]
已经解决。
