### ISSUE TITLE
点右上角打勾的时候，为什么每个图片都会重新刷新

### ISSUE THREAD

**Issue by zk0301** [jeasonlzy/ImagePicker#73]
如题

**Comment by caocao123** [comment]
我也遇到了，我在想是不是加载图片的框架问题

**Comment by nanchen2251** [comment]
在低性能的手机上，GridView每次调用全局刷新，导致这样的情况发生，后面我会考虑用RecyclerView做局部刷新就可以解决了。

**Comment by nanchen2251** [comment]
测试发现更换为RecyclerView也不能解决这个问题，但是如果采用Glide加载是不会出现问题的，只有Picasso才会出现。
