### ISSUE TITLE
还是没有解决android 7.0适配的问题

### ISSUE THREAD

**Issue by mjbstc** [jeasonlzy/ImagePicker#85]
android 7.0后，必须通过provider方式来解决调用文件系统，而不能直接用Uri.fromFile(createImageFile())，希望大神尽快将这个问题解决掉

**Comment by moonljt521** [comment]
我也遇到了这个问题，希望您能解决！！！！！

**Comment by nanchen2251** [comment]
7.0的崩溃问题，我已经可以解决，近期我会贡献自己的代码，到时候就看廖大神merge不了。
