### ISSUE TITLE
关于无法打开图片预览问题

### ISSUE THREAD

**Issue by p-jie** [jeasonlzy/ImagePicker#87]
看了下作者的源码，无法打开图片预览，甚至崩溃是因为在选择图片的时候没有添加到引用里面的，所以导致data的size为0，在get的时候就会出错

解决办法在点击预览的时候，应该把选择图片的list添加到弱引用中
在ImageGridActivity 第138行 添加DataHolder.getInstance().save(DataHolder.DH_CURRENT_IMAGE_FOLDER_ITEMS, imagePicker.getSelectedImages());

**Comment by byronk** [comment]
使用0.4.2的代码，在多选图片时，如果选择一个目录，例如Camera，则可以预览，如果使用默认的“全部图片“，则预览死机

**Comment by byronk** [comment]
死机的问题还是因为数据量大，不能通过Intent.putExtra来传递，建议根据预览的类型，直接在预览窗口中调用ImagePicker.getInstance().getSelectedImages()或者ImagePicker.getInstance().getCurrentImageFolderItems()来获取图片列表

**Comment by nanchen2251** [comment]
OK，这个问题会在近期修复。主要是Intent问题。
