### ISSUE TITLE
ImagePicker 文件适配了7.0，没有对版本进行处理，会导致低版本的相机拍照没有照片

### ISSUE THREAD

**Issue by BaiShou** [jeasonlzy/ImagePicker#91]
应该改为：
                 Uri uri;
                if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) {
                    /**
                     * 7.0 调用系统相机拍照不再允许使用Uri方式，应该替换为FileProvider
                     * 并且这样可以解决MIUI系统上拍照返回size为0的情况
                     */
                    uri = FileProvider.getUriForFile(activity, "com.lzy.imagepicker.provider", takeImageFile);
                } else {
                    uri = Uri.fromFile(takeImageFile);
                }

**Comment by nanchen2251** [comment]
好的
