### ISSUE TITLE
项目中使用报provider错误，导致程序无法安装

### ISSUE THREAD

**Issue by ping999** [jeasonlzy/ImagePicker#94]
背景：目前服务端 / 用户端的两个项目，均引用了同一模块（也可以说是libary），模块主要是封装常用的方法。
现象：服务端APP运行安装成功，运行用户端APP时studio提醒“INSTALL_FAILED_UPDATE_INCOMPATIBLE”，查看log如下：
log：Can't install because provider name com.lzy.imagepicker.provider (in package zwp.zcyke.user) is already used by zwp.zcyke.yaojiserver

**Comment by ping999** [comment]
![default](https://cloud.githubusercontent.com/assets/20810003/24090805/71737676-0d7e-11e7-9547-0cf46f136d7f.png)
![default](https://cloud.githubusercontent.com/assets/20810003/24090806/7178bcbc-0d7e-11e7-9ca8-e5f41bd0a004.png)

**Comment by nanchen2251** [comment]
这个是因为provider不能重复，请把ImagePicker作为module引入，并且把名字更改为不一样的provider的名字即可。

**Comment by nanchen2251** [comment]
<provider
            android:authorities="${applicationId}.provider"
            android:name="android.support.v4.content.FileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>


我这里是采用的动态生成的${applicationId}做的不一样的限制。

**Comment by ping999** [comment]
需要手动修改authorities吗

**Comment by nanchen2251** [comment]
对，只需要把那个authorities更改了，再ImagePicker的takePicture再更改一下就可以了。

Uri uri = FileProvider.getUriForFile(activity, BuildConfig.APPLICATION_ID + ".provider", takeImageFile);
                takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, uri);

**Comment by nanchen2251** [comment]
我是用的ApplicationId做的处理。

**Comment by ping999** [comment]
能否像这样动态的生成authorities：android:authorities="${applicationId}.fileprovider"

https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/AndroidManifest.xml

**Comment by ping999** [comment]
本地化很不利于功能迭代，烦请解决下这个问题咯
