### ISSUE TITLE
之前用studio 自动引入过并且选择引入最新版本的注意了

### ISSUE THREAD

**Issue by weills** [jeasonlzy/ImagePicker#95]
由于这个库最新版的编译版本，Target版本都是最新的25，如果你的工程不是这个版本的话，自动引入且是最新版本的话会发生莫名其妙的问题，例如引用高版本资源文件找不到，design包控件类找不到等奇奇怪怪的错误，下载下来作为module导入再修改下就好啦。话说这个问题实在是困惑我好久

**Comment by nanchen2251** [comment]
这个问题，实在不好意思了，后面会在文档中说明的。
