### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by a48352433** [jeasonlzy/ImagePicker#98]
刚想提这个问题.发现已经解决了- -!而且还换人了!!!!!!

**Comment by a48352433** [comment]
貌似冲突还在啊...
        android:authorities="com.lzy.imagepicker.provider"
        android:name=".ImagePickerProvider"
这么写还是固定的把authorities始终不变啊!name也不会变!

**Comment by nanchen2251** [comment]
name的冲突只有多个项目引用同一个才会冲突，如果想彻底解决，可以采用引入Module，并把module的代码放到你的主工程去，采用你应用包名来限制这个provider的名字，这里解决冲突的方式，主要是解决你应用的provider和imagepicker的provider.

**Comment by nanchen2251** [comment]
也就是说，这极有可能是我们的一个过渡版本。

**Comment by a48352433** [comment]
也就是说如果不引入module..那么如果别人手机上先装了一个用了这个库的app..在装另一个用这个库的app.而且都不是用的引入module.那么另一个就装不上了是吧!

**Comment by nanchen2251** [comment]
目前可能会这样。所以这是一个比较焦灼的问题。但这还没有在release上面测试，你可以自己加以测试一下。

**Comment by a48352433** [comment]
好的!
